saleor/dashboard/customer/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.customer_list, name='customers'),
    url(r'^(?P<pk>[0-9]+)/$', views.customer_details, name='customer-details')
]

saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.OrderListView.as_view(), name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group')]

saleor/dashboard/payments/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.PaymentList.as_view(), name='payments'),
    url(r'^(?P<pk>[0-9]+)/$', views.payment_details, name='payment-details')
]

saleor/dashboard/search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.search, name='search')
]

saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .order.urls import urlpatterns as order_urls
from .payments.urls import urlpatterns as payments_urls
from .product.urls import urlpatterns as product_urls
from .discount.urls import urlpatterns as discount_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^payments/', include(payments_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^search/', include(search_urls)),
    url(r'^shipping/', include(shipping_urls)),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .dashboard.urls import urlpatterns as dashboard_urls


admin.autodiscover()

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^account/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/cart/models.py
from __future__ import unicode_literals

from collections import namedtuple
from decimal import Decimal
from uuid import uuid4

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible, smart_str
from django.utils.timezone import now
from django.utils.translation import pgettext_lazy
from django_prices.models import PriceField
from jsonfield import JSONField
from satchless.item import ItemLine, ItemList, partition

from . import logger


CENTS = Decimal('0.01')
SimpleCart = namedtuple('SimpleCart', ('quantity', 'total', 'token'))


class ProductGroup(ItemList):
    def is_shipping_required(self):
        return any(p.is_shipping_required() for p in self)


class CartQueryset(models.QuerySet):

    def anonymous(self):
        return self.filter(user=None)

    def open(self):
        return self.filter(status=Cart.OPEN)

    def saved(self):
        return self.filter(status=Cart.SAVED)

    def waiting_for_payment(self):
        return self.filter(status=Cart.WAITING_FOR_PAYMENT)

    def checkout(self):
        return self.filter(status=Cart.CHECKOUT)

    def canceled(self):
        return self.filter(status=Cart.CANCELED)

    def save(self):
        self.update(status=Cart.SAVED)

    def for_display(self):
        return self.prefetch_related(
            'lines',
            'lines__variant',
            'lines__variant__product',
            'lines__variant__product__images',
            'lines__variant__product__product_class__product_attributes',
            'lines__variant__product__product_class__product_attributes__values',  # noqa
            'lines__variant__product__product_class__variant_attributes',
            'lines__variant__product__product_class__variant_attributes__values',  # noqa
            'lines__variant__stock')


class Cart(models.Model):

    COOKIE_NAME = 'cart'

    OPEN, SAVED, WAITING_FOR_PAYMENT, ORDERED, CHECKOUT, CANCELED = (
        'open', 'saved', 'payment', 'ordered', 'checkout', 'canceled')

    STATUS_CHOICES = (
        (OPEN, pgettext_lazy('Cart', 'Open - currently active')),
        (WAITING_FOR_PAYMENT, pgettext_lazy('Cart', 'Waiting for payment')),
        (SAVED, pgettext_lazy(
            'Cart', 'Saved - for items to be purchased later')),
        (ORDERED, pgettext_lazy(
            'Cart', 'Submitted - has been ordered at the checkout')),
        (CHECKOUT, pgettext_lazy(
            'Cart', 'Checkout - basket is processed in checkout')),
        (CANCELED, pgettext_lazy(
            'Cart', 'Canceled - basket was canceled by user'))
    )

    status = models.CharField(
        pgettext_lazy('Cart', 'order status'),
        max_length=32, choices=STATUS_CHOICES, default=OPEN)
    created = models.DateTimeField(
        pgettext_lazy('Cart', 'created'), auto_now_add=True)
    last_status_change = models.DateTimeField(
        pgettext_lazy('Cart', 'last status change'), auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, related_name='carts',
        verbose_name=pgettext_lazy('Cart', 'user'))
    email = models.EmailField(blank=True, null=True)
    token = models.UUIDField(pgettext_lazy('Cart', 'token'),
                             primary_key=True, default=uuid4, editable=False)
    voucher = models.ForeignKey('discount.Voucher', null=True,
                                related_name='+', on_delete=models.SET_NULL)
    checkout_data = JSONField(null=True, editable=False)

    total = PriceField(
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2,
        default=0)
    quantity = models.PositiveIntegerField(default=0)

    objects = CartQueryset.as_manager()

    class Meta:
        ordering = ('-last_status_change',)

    def __init__(self, *args, **kwargs):
        self.discounts = kwargs.pop('discounts', None)
        super(Cart, self).__init__(*args, **kwargs)

    def update_quantity(self):
        total_lines = self.count()['total_quantity']
        if not total_lines:
            total_lines = 0
        self.quantity = total_lines
        self.save(update_fields=['quantity'])

    def change_status(self, status):
        if status not in dict(self.STATUS_CHOICES):
            raise ValueError('Not expected status')
        if status != self.status:
            self.status = status
            self.last_status_change = now()
            self.save()

    def change_user(self, user):
        open_cart = Cart.get_user_open_cart(user)
        if open_cart is not None:
            open_cart.change_status(status=Cart.CANCELED)
        self.user = user
        self.save(update_fields=['user'])

    @staticmethod
    def get_user_open_cart(user):
        carts = user.carts.open()
        if len(carts) > 1:
            logger.warning('%s has more than one open basket', user)
            for cart in carts[1:]:
                cart.change_status(Cart.CANCELED)
        return carts.first()

    def is_shipping_required(self):
        return any(line.is_shipping_required() for line in self.lines.all())

    def __repr__(self):
        return 'Cart(quantity=%s)' % (self.quantity,)

    def __len__(self):
        return self.lines.count()

    def get_subtotal(self, item, **kwargs):
        return item.get_total(**kwargs)

    def get_total(self, **kwargs):
        subtotals = [self.get_subtotal(item, **kwargs)
                     for item in self.lines.all()]
        if not subtotals:
            raise AttributeError('Calling get_total() on an empty item set')
        return sum(subtotals[1:], subtotals[0])

    def count(self):
        lines = self.lines.all()
        return lines.aggregate(total_quantity=models.Sum('quantity'))

    def clear(self):
        self.delete()

    def create_line(self, variant, quantity, data):
        line = self.lines.create(variant=variant, quantity=quantity,
                                 data=data or {})
        return line

    def get_line(self, variant, data=None):
        all_lines = self.lines.all()
        if data is None:
            data = {}
        line = [line for line in all_lines
                if line.variant_id == variant.id and line.data == data]
        if line:
            return line[0]

    def add(self, variant, quantity=1, data=None, replace=False,
            check_quantity=True):
        cart_line, created = self.lines.get_or_create(
            variant=variant, defaults={'quantity': 0, 'data': data or {}})
        if replace:
            new_quantity = quantity
        else:
            new_quantity = cart_line.quantity + quantity

        if new_quantity < 0:
            raise ValueError('%r is not a valid quantity (results in %r)' % (
                quantity, new_quantity))

        if check_quantity:
            variant.check_quantity(new_quantity)

        cart_line.quantity = new_quantity

        if not cart_line.quantity:
            cart_line.delete()
        else:
            cart_line.save(update_fields=['quantity'])
        self.update_quantity()

    def partition(self):
        grouper = (
            lambda p: 'physical' if p.is_shipping_required() else 'digital')
        return partition(self.lines.all(), grouper, ProductGroup)


@python_2_unicode_compatible
class CartLine(models.Model, ItemLine):

    cart = models.ForeignKey(Cart, related_name='lines')
    variant = models.ForeignKey(
        'product.ProductVariant', related_name='+',
        verbose_name=pgettext_lazy('Cart line', 'product'))
    quantity = models.PositiveIntegerField(
        pgettext_lazy('Cart line', 'quantity'),
        validators=[MinValueValidator(0), MaxValueValidator(999)])
    data = JSONField(blank=True, default={})

    class Meta:
        unique_together = ('cart', 'variant', 'data')

    def __str__(self):
        return smart_str(self.variant)

    def __eq__(self, other):
        if not isinstance(other, CartLine):
            return NotImplemented

        return (self.variant == other.variant and
                self.quantity == other.quantity and
                self.data == other.data)

    def __ne__(self, other):
        return not self == other  # pragma: no cover

    def __repr__(self):
        return 'CartLine(variant=%r, quantity=%r, data=%r)' % (
            self.variant, self.quantity, self.data)

    def __getstate__(self):
        return self.variant, self.quantity, self.data

    def __setstate__(self, data):
        self.variant, self.quantity, self.data = data

    def get_total(self, **kwargs):
        amount = super(CartLine, self).get_total(**kwargs)
        return amount.quantize(CENTS)

    def get_quantity(self, **kwargs):
        return self.quantity

    def get_price_per_item(self, discounts=None, **kwargs):
        return self.variant.get_price_per_item(discounts=discounts, **kwargs)

    def is_shipping_required(self):
        return self.variant.is_shipping_required()

saleor/dashboard/search/forms.py
from ...search.backends import get_search_backend
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):

    def search(self, queryset_map=None):
        backend = get_search_backend('dashboard')
        query = self.cleaned_data['q']
        results = backend.search(query, queryset_map=queryset_map)
        return results

saleor/dashboard/customer/views.py
from __future__ import unicode_literals

from django.db.models import Count, Max
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from .forms import CustomerSearchForm
from ..views import staff_member_required
from ...core.utils import get_paginator_items
from ...userprofile.models import User


@staff_member_required
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .annotate(
            num_orders=Count('orders', distinct=True),
            last_order=Max('orders', distinct=True)))

    form = CustomerSearchForm(request.GET or None, queryset=customers)
    form_values = [(field.name, field.value() or '') for field in form]
    if form.is_valid():
        customers = form.search()
    else:
        customers = customers.filter(
            orders__status__in=['new', 'payment-pending', 'fully-paid'])
    title = _('Results (%s)') % len(customers)

    customers = get_paginator_items(customers, 30, request.GET.get('page'))
    ctx = {'customers': customers, 'form': form, 'title': title,
           'default_pagination_params': form_values}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related('default_billing_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)

saleor/dashboard/payments/views.py
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.views.generic import ListView
from payments.models import PAYMENT_STATUS_CHOICES

from ..views import (FilterByStatusMixin, StaffMemberOnlyMixin,
                     staff_member_required)
from ...order.models import Payment
from ..order.forms import PaymentFilterForm


class PaymentList(StaffMemberOnlyMixin, FilterByStatusMixin, ListView):
    model = Payment
    template_name = 'dashboard/payments/list.html'
    context_object_name = 'payments'
    paginate_by = 30
    form_class = PaymentFilterForm
    status_choices = PAYMENT_STATUS_CHOICES
    status_order = ['waiting', 'input', 'preauth', 'confirmed', 'refunded',
                    'rejected', 'error']

    def get_queryset(self):
        qs = super(PaymentList, self).get_queryset()
        return qs.order_by('-created').select_related('order')


@staff_member_required
def payment_details(request, pk):
    payment = get_object_or_404(Payment, pk=pk)
    return TemplateResponse(request, 'dashboard/payments/detail.html',
                            {'payment': payment})

templates/dashboard/payments/detail.html
{% extends "dashboard/base.html" %}
{% load prices_i18n %}
{% load i18n %}
{% load status %}
{% load utils %}

{% block title %}{% trans "Payment" %} #{{ payment.id }} - {% trans "Payments" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-payments{% endblock %}

{% block menu_payments_class %}active{% endblock %}

{% block header_menu %}
    {% url "dashboard:payments" as url %}
    {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--history">
        <li><a href="{% url "dashboard:payments" %}">{% trans "Payments" %}</a></li>
        <li class="back-mobile"><a href="{% url "dashboard:payments" %}"><i class="material-icons">arrow_back</i></a></li>
        <li><span>#{{ payment.id }}</span></li>
    </ul>
{% endblock %}

{% block menu_sales_class %} active{% endblock %}

{% block content %}
<div class="row">
    <div class="col s12 l8">
        <div class="card grey lighten-4">
            <div class="card-content">
                <span class="card-title black-text">Payment details</span>

                <ul>
                    <li>{% trans "Payment status" %}: {% render_status payment.status payment.get_status_display %}</li>
                    <li>{% trans "Fraud status" %}: {% render_status payment.fraud_status payment.get_fraud_status_display %}</li>
                    <li>{% trans "Amount" %}: {% gross payment.get_total_price %}</li>
                    <li>{% trans "Captured amount" %}: {% gross payment.get_captured_price %}</li>
                    <li>{% trans "Gateway" %}: {{ payment.variant }}</li>
                    <li>{% trans "Transaction ID" %}: {{ payment.transaction_id }}</li>
                    <li>{% trans "Payment date" %}: {{ payment.created }}</li>
                </ul>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <span class="card-title black-text">{% trans "Gateway response" %}</span>

                {% if payment.message %}
                    {{ payment.message }}
                {% else %}
                    <p>{% trans "No response available." %}</p>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="col s12 l4">
        <div class="row">
            <div class="col s12 m6 l12">
                <div class="card equal-height-on-med">
                    <div class="card-content">
                        <span class="card-title black-text">{% trans "Customer" %}</span>

                        <div class="address">
                            {% if payment.order.user %}
                                <div>{% trans "Account" %}: <a href="{% url "dashboard:customer-details" pk=payment.order.user.pk %}">{{ payment.order.user }}</a></div>
                            {% else %}
                                <div>{% trans "Account" %}: {% trans "Guest" %}</div>
                            {% endif %}
                            <div><i class="material-icons">email</i> <a href="mailto:{{ payment.order.user_email }}">{{ payment.order.user_email }}</a></div>
                            <div>Customer IP: {{ payment.customer_ip_address }}</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col s12 m6 l12">
                <div class="card equal-height-on-med">
                    <div class="card-content">
                        <span class="card-title black-text">{% trans "Billing address" %}</span>

                        <div class="address">
                            <strong>{{ payment.billing_first_name }} {{ payment.billing_last_name }}</strong>
                            <div>{{ payment.billing_address_1 }}</div>
                            {% if payment.payment.billing_address_2 %}
                                <div>{{ payment.payment.billing_address_2 }}</div>
                            {% endif %}
                            <div>{{ payment.billing_postcode }}</div>
                            <div>{{ payment.billing_city }}, {{ payment.billing_country_code }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/payments/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load prices_i18n %}
{% load status %}

{% block title %}{% trans "Payments" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-payments{% endblock %}

{% block menu_payments_class %}active{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs">
        <li class="visible-s">{% trans "Payments" %}</li>
    </ul>
{% endblock %}

{% block content %}
    {% include "dashboard/includes/_status_filters.html" %}

    {% if payments %}
        <div class="card">
            <div class="data-table-container">
                <table class="bordered hoverable responsive data-table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>{% trans "Date" %}</th>
                            <th>{% trans "Payment" %}</th>
                            <th class="right-align">{% trans "Amount" %}</th>
                            <th class="wide">{% trans "Status" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for payment in payments %}
                        <tr>
                            <td><a href="{% url "dashboard:payment-details" pk=payment.pk %}">#{{ payment.id }}</a></td>
                            <td>{{ payment.created }}</td>
                            <td>
                                {% trans "Gateway" %}: {{ payment.variant }} &middot;
                                <a href="{% url 'dashboard:order-details' order_pk=payment.order.pk %}"> {% trans "Order " %}{{ payment.order }}</a>
                            </td>
                            <td class="right-align">{% gross payment.get_total_price %}</td>
                            <td>{% render_status payment.status payment.get_status_display %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        {% include "dashboard/includes/_pagination.html" %}
    {% else %}
        <p>{% trans "No payments found." %}</p>
    {% endif %}

{% endblock %}